### PR TITLE
Selectively import tables with a customized callback per table

### PR DESCRIPTION
**Pull request by dgtized**
Add `LiveFixture#override(table_name, proc)` as a means of overriding the fixture insertion selectively. Basic usage is:

```ruby
importer = LiveFixtures::Import.new(...).
  override('users', ->(label_to_id) { label_to_id['user_fred'] = User.create(name: 'Fred').id })
importer.import_all
```

This allows insertion of tables that do not depend on fixtures. For now though those tables still need to be in the list of files of the directory being imported, but instead of inserting fixtures from those files it will kick out to the callback and allow it to override the data inserted.

### CODE REVIEW

**Comment by asterite** [comment]
💭 Right now the `import_some` method looks like this:

```ruby
importer.import_some(['users']) do |table_name, label_to_id|
  case table_name
  when 'users'
    #...
  end
end
```

So we need to mention `users` in the `import_some` argument and then also in the `case` below.

What do you think about passing a hash with procs, something like:

```ruby
overrides = {
  'users' => lambda { |table_name, label_to_id| }
}

importer.import_some(overrides)
```

And then we could define a class per override which has a `call` method, etc.

**Comment by michaelglass** [comment]
@Arkham @ckoster22 do you have a sense of what's preventing this from getting merged?

**Comment by Arkham** [comment]
I have no idea on the purpose of the branch, but I have been using it and it works. I think @asterite might be the person with the more context here.

**Comment by ckoster22** [comment]
Sorry, I don't have context on whether this is mergeable

**Comment by michaelglass** [comment]
We've been using it in prod for six months. If it doesn't work, we can fix it. As far as I know, this is only used internally.

**Pull request merged**
