### PR TITLE
Support serialized attributes

### PR DESCRIPTION
**Pull request by SamGerber-zz**
#### What it does

This PR adds logic to the export path for a model, that checks if the attribute is meant to be serialized and performs db compatible serialization if it is.

#### Issue

Outfoxes: #10

### CODE REVIEW

**Comment by tesk9** [comment]
Sam, I had some trouble getting this running.

For one, I think your other PR removed the sync_2015_mastery_scores task.

And then I had this output on the export step:
```
➜  NoRedInk git:(seed-without-syncing-mastery-progress) tammy_id=$(bundle exec rails runner "puts User.find_by_email('teacher@noredink.com').id")
blah blah rails 4 messages
➜  NoRedInk git:(seed-without-syncing-mastery-progress) $ bundle exec rake export_data:for_teacher[$tammy_id]

zsh: no matches found: export_data:for_teacher[8168223\nUsage:\n  rails new APP_PATH [options]\n\nOptions:\n  -r, [--ruby=PATH]                                      # Path to the Ruby binary of your choice\n                                                         # Default: /Users/tessakelly/.rubies/ruby-2.3.3/bin/ruby\n  -m, [--template=TEMPLATE]                              # Path to some application template (can be a filesystem path or URL)\n      [--skip-gemfile], [--no-skip-gemfile]              # Don't create a Gemfile\n  -B, [--skip-bundle], [--no-skip-bundle]                # Don't run bundle install\n  -G, [--skip-git], [--no-skip-git]                      # Skip .gitignore file\n      [--skip-keeps], [--no-skip-keeps]                  # Skip source control .keep files\n  -O, [--skip-active-record], [--no-skip-active-record]  # Skip Active Record files\n  -S, [--skip-sprockets], [--no-skip-sprockets]          # Skip Sprockets files\n      [--skip-spring], [--no-skip-spring]                # Don't install Spring application preloader\n  -d, [--database=DATABASE]                              # Preconfigure for selected database (options: mysql/oracle/postgresql/sqlite3/frontbase/ibm_db/sqlserver/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)\n                                                         # Default: sqlite3\n  -j, [--javascript=JAVASCRIPT]                          # Preconfigure for selected JavaScript library\n                                                         # Default: jquery\n  -J, [--skip-javascript], [--no-skip-javascript]        # Skip JavaScript files\n      [--dev], [--no-dev]                                # Setup the application with Gemfile pointing to your Rails checkout\n      [--edge], [--no-edge]                              # Setup the application with Gemfile pointing to Rails repository\n      [--skip-turbolinks], [--no-skip-turbolinks]        # Skip turbolinks gem\n  -T, [--skip-test-unit], [--no-skip-test-unit]          # Skip Test::Unit files\n      [--rc=RC]                                          # Path to file containing extra configuration options for rails command\n      [--no-rc], [--no-no-rc]                            # Skip loading of extra configuration options from .railsrc file\n\nRuntime options:\n  -f, [--force]                    # Overwrite files that already exist\n  -p, [--pretend], [--no-pretend]  # Run but do not make any changes\n  -q, [--quiet], [--no-quiet]      # Suppress status output\n  -s, [--skip], [--no-skip]        # Skip files that already exist\n\nRails options:\n  -h, [--help], [--no-help]        # Show this help message and quit\n  -v, [--version], [--no-version]  # Show Rails version number and quit\n\nDescription:\n    The 'rails new' command creates a new Rails application with a default\n    directory structure and configuration at the path you specify.\n\n    You can specify extra command-line arguments to be used every time\n    'rails new' runs in the .railsrc configuration file in your home directory.\n\n    Note that the arguments specified in the .railsrc file don't affect the\n    defaults values shown above in this help message.\n\nExample:\n    rails new ~/Code/Ruby/weblog\n\n    This generates a skeletal Rails installation in ~/Code/Ruby/weblog.\n    See the README in the newly created application to get going.]
```

Which looks like it comes down the $tammy_id having some rando extras:
```
NoRedInk git:(seed-without-syncing-mastery-progress) echo $tammy_id
8168223
Usage:
  rails new APP_PATH [options]

Options:
  -r, [--ruby=PATH]                                      # Path to the Ruby binary of your choice
                                                         # Default: /Users/tessakelly/.rubies/ruby-2.3.3/bin/ruby
  -m, [--template=TEMPLATE]                              # Path to some application template (can be a filesystem path or URL)
      [--skip-gemfile], [--no-skip-gemfile]              # Don't create a Gemfile
  -B, [--skip-bundle], [--no-skip-bundle]                # Don't run bundle install
  -G, [--skip-git], [--no-skip-git]                      # Skip .gitignore file
      [--skip-keeps], [--no-skip-keeps]                  # Skip source control .keep files
  -O, [--skip-active-record], [--no-skip-active-record]  # Skip Active Record files
  -S, [--skip-sprockets], [--no-skip-sprockets]          # Skip Sprockets files
      [--skip-spring], [--no-skip-spring]                # Don't install Spring application preloader
  -d, [--database=DATABASE]                              # Preconfigure for selected database (options: mysql/oracle/postgresql/sqlite3/frontbase/ibm_db/sqlserver/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)
blah blah more stuff
```

Then using what I believe is actually Tammy's id:
```
 NoRedInk git:(seed-without-syncing-mastery-progress) bundle exec rake export_data:for_teacher['8168223']

zsh: no matches found: export_data:for_teacher[8168223]
```

Do you have a sense of what might be wrong?

**Comment by SamGerber** [comment]
Oof. That's 0 for 2. Sorry. Looking now.

**Comment by SamGerber** [comment]
You're so right about the sync_mastery_scores.

I updated the review instructions to skip that step.

The assignment of tammy's idea is maybe a zsh thing? It looks like it works fine on my system, but no worries, just using the id is great:
```
sam at sams-MacBook-Pro-2 in ~/NoRedInk on seed-without-syncing-mastery-progress
$ tammy_id=$(bundle exec rails runner "puts User.find_by_email('teacher@noredink.com').id")
sam at sams-MacBook-Pro-2 in ~/NoRedInk on seed-without-syncing-mastery-progress
$ echo $tammy_id
8168223
sam at sams-MacBook-Pro-2 in ~/NoRedInk on seed-without-syncing-mastery-progress
$ bundle exec rake export_data:for_teacher[$tammy_id]
User: |===========================================================================================================================================================================| 100.00% Time: 00:00:00
...
```

It seems weird that zsh is trying to match export_data:for_teacher[8168223]...it's just the name of the rake task. 

When you run `bundle exec rake -T export_data` does the `export_data:for_teacher[teacher_id]` come up?

In any case, this version of the gem is what we used to create the new seeds, so we have at least an inkling that the output is sane.

**Pull request merged**
